
services:
  cimex_web:
    image: odoo:16
    depends_on:
      - cimex_db
    ports:
      - "8069:8069"
    volumes:
      - cimex-odoo-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=cimex_db
      - USER=odoo
      - PASSWORD=odoo
  cimex_db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - cimex-odoo-db:/var/lib/postgresql/data
volumes:
  cimex-odoo-data:
  cimex-odoo-db:

